### ISSUE TITLE
How define another style for Modal? 

### ISSUE THREAD

**Issue by Anastasiya2310** [xue2han/react-dynamic-modal#5]
I can't add fix on Modal.js (My team install this package and receive default style) or how can I add class for overlay and content?

**Comment by xue2han** [comment]
Just pass your own style to the Modal,it will override the default style

**Comment by Anastasiya2310** [comment]
cool, but when I put this code and my colleagues pull my shanges and start 'npm install' they will receive default style, right?

**Comment by xue2han** [comment]
No.The default style will be always overridden if you pass custom style to Modal.

**Comment by Anastasiya2310** [comment]
great, thanks
